### PR TITLE
Pull request from Contract Generation

### PR DESCRIPTION
**Pull request by QuentinNev**
Contract generation is pratically finished, except these two points : 

1. Fill the switch case : Because we can't automatically match the markups name in the text with the fields in database, we need a switch case for each markups which will match it with the correct data and then replace it. Not enough time to do so. Another solution would be to name the markups with the same name in database but I don't think it would be very secure.

2. Find out why str_replace doesn't replace anything : Strange behaviour from this method with no error occuring, see comments in ContractController

### CODE REVIEW

**Comment by XCarrel** [comment]
I rejected one change: the button you added in the internship view. There is a button at the bottom of the page.
Also, you MUST improve your debugging methods. I don't want to see:
`<?php if(!empty($out)){ echo '<pre style="text-align: left">'; var_dump($out); echo '</pre>';}?>`
in the view anymore !!!
Instead, use 
`error_log(print_r($out,1));`
in the controller

**Comment by QuentinNev** [comment]
Yes sorry old habits die hard, I'll make an effort to remember the next time.

**Comment by XCarrel** [comment]
As for str_replace you have 2 problems:

1. str_replace returns a string but does not modify the original string
2. foreach works on copies of the items, not the items themselves

Try and study this:
```
        $words = ['hello','world','how'];
        foreach ($words as $word)
            str_replace('l','.',$word);
        error_log("wrong:".print_r($words,1));
        for ($i=0; $i<count($words); $i++)
            str_replace('l','.',$words[$i]);
        error_log("Also wrong:".print_r($words,1));
        for ($i=0; $i<count($words); $i++)
            $words[$i] = str_replace('l','.',$words[$i]);
        error_log("Right:".print_r($words,1));

```

**Comment by XCarrel** [comment]
and to be complete:
```
        foreach ($words as $word)
            $word = str_replace('l','.',$word);
        error_log("Still wrong:".print_r($words,1));

```

**Pull request merged**
